# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options


class TestSmokeTestSuite():
  def setup_method(self, method):
    options = Options()
    options.add_argument("--headless=new")
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_nameandLogoTest(self):
    self.driver.set_window_size(1200, 800)
    self.driver.get("http://localhost:5500/teton/1.6/index.html")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "img[src*='teton-logo']")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, "h1").text == "Teton Idaho"
    assert self.driver.find_element(By.CSS_SELECTOR, "h2").text == "Chamber of Commerce"
    assert self.driver.title == "Teton Idaho CoC"

  def test_homePageTest(self):
    self.driver.set_window_size(1200, 800)
    self.driver.get("http://localhost:5500/teton/1.6/index.html")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "section.main-spotlight")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "a.a-button[href='join.html']")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a.a-button[href='join.html']").click()

  def test_directoryPageTest(self):
    self.driver.set_window_size(1200, 800)
    self.driver.get("http://localhost:5500/teton/1.6/directory.html")
    self.driver.find_element(By.CSS_SELECTOR, "button#directory-grid").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#directory-data")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "button#directory-list").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#directory-data")
    assert len(elements) > 0

  def test_joinPageTest(self):
    self.driver.set_window_size(1200, 800)
    self.driver.get("http://localhost:5500/teton/1.6/join.html")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "input[name='fname']")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "input[name='fname']").send_keys("Josh")
    self.driver.find_element(By.CSS_SELECTOR, "input[type='submit']").click()

  def test_adminPageTest(self):
    self.driver.set_window_size(1200, 800)
    self.driver.get("http://localhost:5500/teton/1.6/admin.html")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "input#username")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "input#username").send_keys("fakeuser")
    self.driver.find_element(By.CSS_SELECTOR, "input#password").send_keys("wrongpass")
    self.driver.find_element(By.CSS_SELECTOR, "input[value='Login']").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "span.errorMessage")
    assert len(elements) > 0
